{
 "title": "Compare System Parameters",
 "description": "Dashboard to view multiple servers",
 "tags": [
  "OS",
  "Percona"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(node_boot_time, instance)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<h1><i><font color=#5991A7><b><center>System Information</center></b></font></i></h1>"
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "$host - System Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "repeat": "host",
   "targets": [
    {
     "expr": "node_uname_info{instance=~\"$host\"}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "$host - System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 },
   "repeat": "host",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time{instance=~\"$host\"} - node_boot_time{instance=~\"$host\"}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "$host - CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
   "repeat": "host",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_cpu{instance=~\"$host\", mode=\"system\"})"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "$host - RAM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 },
   "repeat": "host",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$host\"}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "$host - Saturation Metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "(avg_over_time(node_procs_running{instance=~\"$host\"}[$interval])-1) / scalar(count(node_cpu{mode=\"user\", instance=~\"$host\"})) or (avg_over_time(node_procs_running{instance=~\"$host\"}[5m])-1) / scalar(count(node_cpu{mode=\"user\", instance=~\"$host\"}))",
     "legendFormat": "Normalized CPU Load"
    },
    {
     "calculatedInterval": "2s",
     "expr": "avg_over_time(node_procs_blocked{instance=~\"$host\"}[$interval]) or avg_over_time(node_procs_blocked{instance=~\"$host\"}[5m])",
     "legendFormat": "IO Load "
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "$host - Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$host\"} ",
     "legendFormat": "LoadAvg 1m"
    },
    {
     "expr": "count(node_cpu{mode=\"user\", instance=~\"$host\"})",
     "legendFormat": "VCPUs"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 32 },
   "content": "<h1><i><font color=#5991A7><b><center>CPU</center></b></font></i></h1>"
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "$host - CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "repeat": "host",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max((avg by (mode) ( (clamp_max(rate(node_cpu{instance=~\"$host\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=~\"$host\",mode!=\"idle\"}[5m]),1)) )),1)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu{instance=~\"$host\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=~\"$host\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
     "legendFormat": "Max Core Utilization"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "$host - Interrupts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_intr{instance=~\"$host\"}[$interval]) or irate(node_intr{instance=~\"$host\"}[5m])",
     "legendFormat": "Interrupts"
    },
    {
     "expr": "(rate(node_intr{instance=~\"$host\"}[$interval]) or irate(node_intr{instance=~\"$host\"}[5m])) /scalar(count(node_cpu{mode=\"user\", instance=~\"$host\"}))",
     "legendFormat": "Interrupts per VCPU"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "$host - Context Switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_context_switches{instance=~\"$host\"}[$interval]) or irate(node_context_switches{instance=~\"$host\"}[5m])",
     "legendFormat": "Context Switches"
    },
    {
     "expr": "(rate(node_context_switches{instance=~\"$host\"}[$interval]) or irate(node_context_switches{instance=~\"$host\"}[5m])) / scalar(count(node_cpu{mode=\"user\", instance=~\"$host\"}))",
     "legendFormat": "Context Switches per Virtual CPU"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 59 },
   "content": "<h1><i><font color=#5991A7><b><center>Memory</center></b></font></i></h1>"
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "$host - Memory  Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "max(node_memory_MemTotal{instance=~\"$host\"}) without(job) - \n(max(node_memory_MemFree{instance=~\"$host\"}) without(job) + \nmax(node_memory_Buffers{instance=~\"$host\"}) without(job) + \n(max(node_memory_Cached{instance=~\"$host\",job=~\"rds-enhanced|linux\"}) without (job) or \nmax(node_memory_Cached{instance=~\"$host\",job=\"rds-basic\"}) without (job)))",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree{instance=~\"$host\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Buffers{instance=~\"$host\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "max(node_memory_Cached{instance=~\"$host\",job=~\"rds-enhanced|linux\"}) without (job) or \nmax(node_memory_Cached{instance=~\"$host\",job=~\"rds-basic\"}) without (job)",
     "legendFormat": "Cached"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "$host - Swap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_SwapTotal{instance=~\"$host\"} - node_memory_SwapFree{instance=~\"$host\"}",
     "legendFormat": "Used"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_SwapFree{instance=~\"$host\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_SwapTotal{instance=~\"$host\"}",
     "legendFormat": "Total"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "$host - Swap Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
   "repeat": "host",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpin{instance=~\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{instance=~\"$host\"}[5m]) * 4096",
     "legendFormat": "Swap In (Reads)"
    },
    {
     "expr": "rate(node_vmstat_pswpout{instance=~\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{instance=~\"$host\"}[5m]) * 4096",
     "legendFormat": "Swap Out (Writes)"
    }
   ]
  },
  { "title": "Disk partitions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 86 },
   "content": "<h1><i><font color=#5991A7><b><center>Disk partitions</center></b></font></i></h1>"
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "$host - Mountpoint Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "repeat": "host",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_filesystem_free{instance=~\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"} / node_filesystem_size{instance=~\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "$host - Free Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 97 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free{instance=~\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"} ",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Disk performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 105 },
   "content": "<h1><i><font color=#5991A7><b><center>Disk performance</center></b></font></i></h1>"
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "$host - I/O Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 108 },
   "repeat": "host",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgin{instance=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=~\"$host\"}[5m]) * 1024",
     "legendFormat": "Page In"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgout{instance=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=~\"$host\"}[5m]) * 1024",
     "legendFormat": "Page Out"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "$host - Disk Operations",
   "type": "graph",
   "description": "Shows amount of physical IOs (reads and writes) different devices are serving. Spikes in number of IOs served often corresponds to performance problems due to IO subsystem overload.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 116 },
   "repeat": "host",
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed{instance=~'$host'}[$interval]) or irate(node_disk_reads_completed{instance=~'$host'}[5m])",
     "legendFormat": "Reads: {{device}}"
    },
    {
     "expr": "rate(node_disk_writes_completed{instance=~'$host'}[$interval]) or irate(node_disk_writes_completed{instance=~'$host'}[5m])",
     "legendFormat": "Writes: {{device}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 } },
  {
   "title": "$host - Disk Bandwidth",
   "type": "graph",
   "description": "Shows volume of reads and writes the storage is handling. This can be better measure of IO capacity usage for network attached and SSD storage as it is often bandwidth limited.  Amount of data being written to the disk can be used to estimate Flash storage life time.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 124 },
   "repeat": "host",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_bytes_read{instance=~\"$host\"}[$interval]) or irate(node_disk_bytes_read{instance=~\"$host\"}[5m])",
     "legendFormat": "Reads: {{device}} "
    },
    {
     "expr": "rate(node_disk_bytes_written{instance=~\"$host\"}[$interval]) or irate(node_disk_bytes_written{instance=~\"$host\"}[5m])",
     "legendFormat": "Writes: {{device}} "
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 } },
  {
   "title": "$host - Disk IO Utilization",
   "type": "graph",
   "description": "Shows disk Utilization as percent of the time when there was at least one IO request in flight. It is designed to match utilization available in iostat tool. It is not very good measure of true IO Capacity Utilization. Consider looking at IO latency and Disk Load Graphs instead.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 132 },
   "repeat": "host",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_ms{instance=~\"$host\"}[$interval])/1000 or irate(node_disk_io_time_ms{instance=~\"$host\"}[5m])/1000",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 } },
  {
   "title": "$host - Disk Latency",
   "type": "graph",
   "description": "Shows average latency for Reads and Writes IO Devices.  Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems.  Higher than normal latency also can indicate internal storage problems.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 140 },
   "repeat": "host",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(rate(node_disk_read_time_ms{instance=~\"$host\"}[$interval]) / \nrate(node_disk_reads_completed{instance=~\"$host\"}[$interval])) or \n(irate(node_disk_read_time_ms{instance=~\"$host\"}[5m]) / \nirate(node_disk_reads_completed{instance=~\"$host\"}[5m]))\nor avg_over_time(aws_rds_read_latency_average{instance=~\"$host\"}[$interval]) or \navg_over_time(aws_rds_read_latency_average{instance=~\"$host\"}[5m])",
     "legendFormat": "Read: {{ device }}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "(rate(node_disk_write_time_ms{instance=~\"$host\"}[$interval]) / \nrate(node_disk_writes_completed{instance=~\"$host\"}[$interval])) or \n(irate(node_disk_write_time_ms{instance=~\"$host\"}[5m]) / \nirate(node_disk_writes_completed{instance=~\"$host\"}[5m]))\nor (avg_over_time(aws_rds_write_latency_average{instance=~\"$host\"}[$interval]) or \navg_over_time(aws_rds_write_latency_average{instance=~\"$host\"}[5m]))",
     "legendFormat": "Write: {{ device }}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 } },
  {
   "title": "$host - Disk Load",
   "type": "graph",
   "description": "Shows how much disk was loaded for reads or writes as average number of outstanding requests at different period of time.  High disk load is a good measure of actual storage utilization. Different storage types handle load differently - some will show latency increases on low loads others can handle higher load with no problems.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 148 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_disk_read_time_ms{instance=~\"$host\"}[$interval])/1000 or \nirate(node_disk_read_time_ms{instance=~\"$host\"}[5m])/1000",
     "legendFormat": "Read: {{ device }}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_disk_write_time_ms{instance=~\"$host\"}[$interval])/1000 or \nirate(node_disk_write_time_ms{instance=~\"$host\"}[5m])/1000",
     "legendFormat": "Write: {{ device }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 155 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 156 },
   "content": "<h1><i><font color=#5991A7><b><center>Network</center></b></font></i></h1>"
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 } },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 159 },
   "repeat": "host",
   "yaxes": [
    { "format": "Bps", "label": "bytes out (-) / bytes in (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes{instance=~\"$host\", device!=\"lo\"}[$interval])) or \nsum(irate(node_network_receive_bytes{instance=~\"$host\", device!=\"lo\"}[5m])) or \nsum(max_over_time(rdsosmetrics_network_rx{instance=~\"$host\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_rx{instance=~\"$host\"}[5m])) ",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes{instance=~\"$host\", device!=\"lo\"}[$interval])) or \nsum(irate(node_network_transmit_bytes{instance=~\"$host\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{instance=~\"$host\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_tx{instance=~\"$host\"}[5m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 166 } },
  {
   "title": "Network Utilization Hourly",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 167 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes{instance=~\"$host\", device!=\"lo\"}[1h]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes{instance=~\"$host\", device!=\"lo\"}[1h]))",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}