{
 "title": "Network Overview",
 "description": "Network Overview",
 "tags": [
  "Percona",
  "OS"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(node_boot_time, instance)"
   },
   {
    "name": "device",
    "label": "Device",
    "query": "label_values(node_network_receive_packets{instance=~\"$host\"},device)"
   }
  ]
 },
 "panels": [
  { "title": "Last Hour statistic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Inbound Speed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes{device!=\"lo\",instance=~\"$host\"}[1h]))"
    }
   ]
  },
  {
   "title": "Outbound Speed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes{device!=\"lo\",instance=~\"$host\"}[1h]))"
    }
   ]
  },
  {
   "title": "Traffic Errors and Drops",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_errs{instance=~\"$host\", device!=\"lo\"}[1h])) +\nsum(increase(node_network_transmit_errs{instance=~\"$host\", device!=\"lo\"}[1h])) +\nsum(increase(node_network_receive_drop{instance=~\"$host\", device!=\"lo\"}[1h])) +\nsum(increase(node_network_transmit_drop{instance=~\"$host\", device!=\"lo\"}[1h]))"
    }
   ]
  },
  {
   "title": "Retransmit rate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{instance=~\"$host\"}[1h]) * 100 / (rate(node_netstat_Tcp_OutSegs{instance=~\"$host\"}[1h]) + rate(node_netstat_Tcp_InSegs{instance=~\"$host\"}[1h]))"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes", "label": "bytes out (-) / bytes in (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes{instance=~\"$host\", device!=\"lo\"}[$interval])) or \nsum(irate(node_network_receive_bytes{instance=~\"$host\", device!=\"lo\"}[5m])) or \nsum(max_over_time(rdsosmetrics_network_rx{instance=~\"$host\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_rx{instance=~\"$host\"}[5m])) ",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes{instance=~\"$host\", device!=\"lo\"}[$interval])) or \nsum(irate(node_network_transmit_bytes{instance=~\"$host\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{instance=~\"$host\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_tx{instance=~\"$host\"}[5m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Network Utilization Hourly",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes{instance=~\"$host\", device!=\"lo\"}[1h]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes{instance=~\"$host\", device!=\"lo\"}[1h]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  { "title": "Network traffic details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Network Traffic by Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_packets{instance=~\"$host\", device!=\"lo\"}[$interval]) or \nirate(node_network_receive_packets{instance=~\"$host\", device!=\"lo\"}[5m])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "rate(node_network_transmit_packets{instance=~\"$host\", device!=\"lo\"}[$interval]) or \nirate(node_network_transmit_packets{instance=~\"$host\", device!=\"lo\"}[5m])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_errs{instance=~\"$host\", device!=\"lo\"}[$interval]) or \nirate(node_network_receive_errs{instance=~\"$host\", device!=\"lo\"}[5m])",
     "legendFormat": "{{device}} - Receive errors"
    },
    {
     "expr": "rate(node_network_transmit_errs{instance=~\"$host\", device!=\"lo\"}[$interval]) or\nirate(node_network_transmit_errs{instance=~\"$host\", device!=\"lo\"}[5m])",
     "legendFormat": "{{device}} - Transmit errors"
    }
   ]
  },
  {
   "title": "Network Traffic Drop",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_drop{instance=~\"$host\", device!=\"lo\"}[$interval]) or\nirate(node_network_receive_drop{instance=~\"$host\", device!=\"lo\"}[5m])",
     "legendFormat": "{{device}} - Receive drop"
    },
    {
     "expr": "rate(node_network_transmit_drop{instance=~\"$host\", device!=\"lo\"}[$interval]) or \nirate(node_network_transmit_drop{instance=~\"$host\", device!=\"lo\"}[5m])",
     "legendFormat": "{{device}} - Transmit drop"
    }
   ]
  },
  {
   "title": "Network Traffic Multicast",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_multicast{instance=~\"$host\", device!=\"lo\"}[$interval]) or\nirate(node_network_receive_multicast{instance=~\"$host\", device!=\"lo\"}[5m])",
     "legendFormat": "{{device}} - Receive multicast"
    },
    {
     "expr": "rate(node_network_transmit_multicast{instance=~\"$host\", device!=\"lo\"}[$interval]) or\nirate(node_network_transmit_multicast{instance=~\"$host\", device!=\"lo\"}[5m])",
     "legendFormat": "{{device}} - Transmit multicast"
    }
   ]
  },
  { "title": "Network Netstat TCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Timeout value used for retransmitting",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 34 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_netstat_Tcp_RtoAlgorithm{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Min TCP Retransmission timeout",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 34 },
   "format": "ms",
   "valueName": "min",
   "targets": [
    {
     "expr": "min_over_time(node_netstat_Tcp_RtoMin{instance=~\"$host\"}[$interval])"
    }
   ]
  },
  {
   "title": "Max TCP Retransmission timeout",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 34 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(node_netstat_Tcp_RtoMax{instance=~\"$host\"}[$interval])"
    }
   ]
  },
  {
   "title": "Netstat: TCP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(node_netstat_Tcp_CurrEstab{instance=~\"$host\"}[$interval]) or\nmax_over_time(node_netstat_Tcp_CurrEstab{instance=~\"$host\"}[5m])",
     "legendFormat": "established"
    },
    {
     "expr": "max_over_time(node_netstat_Tcp_ActiveOpens{instance=~\"$host\"}[$interval]) or\nmax_over_time(node_netstat_Tcp_ActiveOpens{instance=~\"$host\"}[5m])",
     "legendFormat": "activeOpens"
    },
    {
     "expr": "max_over_time(node_netstat_Tcp_PassiveOpens{instance=~\"$host\"}[$interval]) or\nmax_over_time(node_netstat_Tcp_PassiveOpens{instance=~\"$host\"}[5m])",
     "legendFormat": "passiveOpens"
    },
    {
     "expr": "max_over_time(node_netstat_Tcp_EstabResets{instance=~\"$host\"}[$interval]) or\nmax_over_time(node_netstat_Tcp_EstabResets{instance=~\"$host\"}[5m])",
     "legendFormat": "estabResets"
    },
    {
     "expr": "max_over_time(node_netstat_Tcp_AttemptFails{instance=~\"$host\"}[$interval]) or\nmax_over_time(node_netstat_Tcp_AttemptFails{instance=~\"$host\"}[5m])",
     "legendFormat": "attemptfails"
    },
    {
     "expr": "max_over_time(node_netstat_Tcp_RetransSegs{instance=~\"$host\"}[$interval]) or\nmax_over_time(node_netstat_Tcp_RetransSegs{instance=~\"$host\"}[5m])",
     "legendFormat": "retransSegs"
    }
   ]
  },
  {
   "title": "TCP Segments",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Out (-) / In (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_InCsumErrors{instance=~\"$host\"}[$interval]) or irate(node_netstat_Tcp_InCsumErrors{instance=~\"$host\"}[5m])",
     "legendFormat": "InCsumErrors"
    },
    {
     "expr": "rate(node_netstat_Tcp_InErrs{instance=~\"$host\"}[$interval]) or irate(node_netstat_Tcp_InErrs{instance=~\"$host\"}[5m])",
     "legendFormat": "InErrs "
    },
    {
     "expr": "rate(node_netstat_Tcp_InSegs{instance=~\"$host\"}[$interval]) or irate(node_netstat_Tcp_InSegs{instance=~\"$host\"}[5m])",
     "legendFormat": "InSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_OutRsts{instance=~\"$host\"}[$interval]) or irate(node_netstat_Tcp_OutRsts{instance=~\"$host\"}[5m])",
     "legendFormat": "OutRsts"
    },
    {
     "expr": "rate(node_netstat_Tcp_OutSegs{instance=~\"$host\"}[$interval]) or irate(node_netstat_Tcp_OutSegs{instance=~\"$host\"}[5m])",
     "legendFormat": "OutSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{instance=~\"$host\"}[$interval]) or irate(node_netstat_Tcp_RetransSegs{instance=~\"$host\"}[5m])",
     "legendFormat": "RetransSegs"
    }
   ]
  },
  { "title": "Network Netstat UDP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Netstat: UDP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Out (-) / In (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_netstat_Udp_InDatagrams{instance=~\"$host\"}[$interval]) or irate(node_netstat_Udp_InDatagrams{instance=~\"$host\"}[5m]))",
     "legendFormat": "Udp_InDatagrams"
    },
    {
     "expr": "sum(rate(node_netstat_Udp_InErrors{instance=~\"$host\"}[$interval]) or irate(node_netstat_Udp_InErrors{instance=~\"$host\"}[5m]))",
     "legendFormat": "Udp_InErrors"
    },
    {
     "expr": "sum(rate(node_netstat_Udp_OutDatagrams{instance=~\"$host\"}[$interval]) or irate(node_netstat_Udp_OutDatagrams{instance=~\"$host\"}[5m]))",
     "legendFormat": "Udp_OutDatagrams"
    },
    {
     "expr": "sum(rate(node_netstat_Udp_NoPorts{instance=~\"$host\"}[$interval]) or irate(node_netstat_Udp_NoPorts{instance=~\"$host\"}[5m]))",
     "legendFormat": "Udp_NoPorts"
    },
    {
     "expr": "sum(rate(node_netstat_Udp_InCsumErrors{instance=~\"$host\"}[$interval]) or irate(node_netstat_Udp_InCsumErrors{instance=~\"$host\"}[5m]))",
     "legendFormat": "Udp_InCsumErrors"
    },
    {
     "expr": "sum(rate(node_netstat_Udp_RcvbufErrors{instance=~\"$host\"}[$interval]) or irate(node_netstat_Udp_RcvbufErrors{instance=~\"$host\"}[5m]))",
     "legendFormat": "Udp_RcvbufErrors"
    },
    {
     "expr": "sum(rate(node_netstat_Udp_SndbufErrors{instance=~\"$node\"}[$interval]) or irate(node_netstat_Udp_SndbufErrors{instance=~\"$host\"}[5m]))",
     "legendFormat": "Udp_SndbufErrors"
    }
   ]
  },
  {
   "title": "UDP Lite",
   "type": "graph",
   "description": "**InDatagrams** Packets received\n\n**OutDatagrams** Packets sent\n\n**InCsumErrors** Datagrams with checksum errors\n\n**InErrors** Datagrams that could not be delivered to an application\n\n**RcvbufErrors** Datagrams for which not enough socket buffer memory to receive\n\n**SndbufErrors**  Datagrams for which not enough socket buffer memory to transmit\n\n**NoPorts**  Datagrams received on a port with no listener",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "ops", "label": "Out (-) / In (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_UdpLite_InDatagrams{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_UdpLite_InDatagrams{instance=~\"$host\"}[5m])",
     "legendFormat": "InDatagrams "
    },
    {
     "expr": "rate(node_netstat_UdpLite_OutDatagrams{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_UdpLite_OutDatagrams{instance=~\"$host\"}[5m])",
     "legendFormat": "OutDatagrams "
    },
    {
     "expr": "rate(node_netstat_UdpLite_InCsumErrors{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_UdpLite_InCsumErrors{instance=~\"$host\"}[5m])",
     "legendFormat": "InCsumErrors"
    },
    {
     "expr": "rate(node_netstat_UdpLite_InErrors{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_UdpLite_InErrors{instance=~\"$host\"}[5m])",
     "legendFormat": "InErrors "
    },
    {
     "expr": "rate(node_netstat_UdpLite_RcvbufErrors{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_UdpLite_RcvbufErrors{instance=~\"$host\"}[5m])",
     "legendFormat": "RcvbufErrors "
    },
    {
     "expr": "rate(node_netstat_UdpLite_SndbufErrors{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_UdpLite_SndbufErrors{instance=~\"$host\"}[5m])",
     "legendFormat": "SndbufErrors "
    },
    {
     "expr": "rate(node_netstat_UdpLite_NoPorts{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_UdpLite_NoPorts{instance=~\"$host\"}[5m])",
     "legendFormat": "NoPorts"
    }
   ]
  },
  { "title": "ICMP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "ICMP Errors",
   "type": "graph",
   "description": "**InErrors**  Messages which the entity received but determined as having ICMP-specific errors (bad ICMP checksums, bad length, etc.)\n\n**OutErrors** Messages which this entity did not send due to problems discovered within ICMP, such as a lack of buffers\n\n**InDestUnreachs**  Destination Unreachable messages received\n\n**OutDestUnreachs** Destination Unreachable messages sent\n\n**InType3** Destination unreachable\n\n**OutType3** Destination unreachable\n\n**InCsumErrors** Messages with ICMP checksum errors\n\n**InTimeExcds** Time Exceeded messages received",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "ops", "label": "Out (-) / In (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Icmp_InErrors{instance=~\"$host\"}[$interval]) \nor irate(node_netstat_Icmp_InErrors{instance=~\"$host\"}[5m])",
     "legendFormat": "InErrors"
    },
    {
     "expr": "rate(node_netstat_Icmp_OutErrors{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_Icmp_OutErrors{instance=~\"$host\"}[5m])",
     "legendFormat": "OutErrors"
    },
    {
     "expr": "rate(node_netstat_Icmp_InDestUnreachs{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_Icmp_InDestUnreachs{instance=~\"$host\"}[5m])",
     "legendFormat": "InDestUnreachs"
    },
    {
     "expr": "rate(node_netstat_Icmp_OutDestUnreachs{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_Icmp_OutDestUnreachs{instance=~\"$host\"}[5m])",
     "legendFormat": "OutDestUnreachs"
    },
    {
     "expr": "rate(node_netstat_IcmpMsg_InType3{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_IcmpMsg_InType3{instance=~\"$host\"}[5m])",
     "legendFormat": "InType3 (Destination unreachable)"
    },
    {
     "expr": "irate(node_netstat_IcmpMsg_OutType3{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_IcmpMsg_OutType3{instance=~\"$host\"}[5m])",
     "legendFormat": "OutType3 (Destination unreachable)"
    },
    {
     "expr": "rate(node_netstat_Icmp_InCsumErrors{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_Icmp_InCsumErrors{instance=~\"$host\"}[5m])",
     "legendFormat": "InCsumErrors"
    },
    {
     "expr": "rate(node_netstat_Icmp_InTimeExcds{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_Icmp_InTimeExcds{instance=~\"$host\"}[5m])",
     "legendFormat": "InTimeExcds"
    }
   ]
  },
  {
   "title": "Messages / Redirects",
   "type": "graph",
   "description": "**InMsgs**  Messages which the entity received. Note that this counter includes all those counted by icmpInErrors\t\n\n**InRedirects**  Redirect messages received\t\n\n**OutMsgs**  Messages which this entity attempted to send. Note that this counter includes all those counted by icmpOutErrors\t\n\n**OutRedirects** Redirect messages sent. For a host, this object will always be zero, since hosts do not send redirects",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "ops", "label": "Out (-) / In (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Icmp_InMsgs{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_Icmp_InMsgs{instance=~\"$host\"}[5m])",
     "legendFormat": "InMsgs "
    },
    {
     "expr": "rate(node_netstat_Icmp_InRedirects{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_Icmp_InRedirects{instance=~\"$host\"}[5m])",
     "legendFormat": "InRedirects"
    },
    {
     "expr": "rate(node_netstat_Icmp_OutMsgs{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_Icmp_OutMsgs{instance=~\"$host\"}[5m])",
     "legendFormat": "OutMsgs"
    },
    {
     "expr": "rate(node_netstat_Icmp_OutRedirects{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_Icmp_OutRedirects{instance=~\"$host\"}[5m])",
     "legendFormat": "OutRedirects"
    }
   ]
  },
  {
   "title": "Echos",
   "type": "graph",
   "description": "**InEchoReps**  Echo Reply messages received\n\n**InEchos**  Echo (request) messages received\n\n**OutEchoReps** Echo Reply messages sent\n\n**OutEchos**  Echo (request) messages sent",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "ops", "label": "Out (-) / In (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Icmp_InEchoReps{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_Icmp_InEchoReps{instance=~\"$host\"}[5m])",
     "legendFormat": "InEchoReps"
    },
    {
     "expr": "rate(node_netstat_Icmp_InEchos{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_Icmp_InEchos{instance=~\"$host\"}[5m])",
     "legendFormat": "InEchos "
    },
    {
     "expr": "rate(node_netstat_Icmp_OutEchoReps{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_Icmp_OutEchoReps{instance=~\"$host\"}[5m])",
     "legendFormat": "OutEchoReps"
    },
    {
     "expr": "rate(node_netstat_Icmp_OutEchos{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_Icmp_OutEchos{instance=~\"$host\"}[5m])",
     "legendFormat": "OutEchos"
    }
   ]
  },
  {
   "title": "Timestamps / Mask Requests",
   "type": "graph",
   "description": "**InAddrMaskReps**  Address Mask Reply messages received\n\n**InAddrMasks** Address Mask Request messages received\n\n**OutAddrMaskReps**  Address Mask Reply messages sent\n\n**OutAddrMasks**  Address Mask Request messages sent\n\n**InTimestampReps**  Timestamp Reply messages received\n\n**InTimestamps**  Timestamp Request messages received\t\n\n**OutTimestampReps** Timestamp Reply messages sent\n\n**OutTimestamps** Timestamp Request messages sent",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short", "label": "out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Icmp_InAddrMaskReps{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_Icmp_InAddrMaskReps{instance=~\"$host\"}[5m])",
     "legendFormat": "InAddrMaskReps"
    },
    {
     "expr": "rate(node_netstat_Icmp_InAddrMasks{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_Icmp_InAddrMasks{instance=~\"$host\"}[5m])",
     "legendFormat": "InAddrMasks"
    },
    {
     "expr": "rate(node_netstat_Icmp_OutAddrMaskReps{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_Icmp_OutAddrMaskReps{instance=~\"$host\"}[5m])",
     "legendFormat": "OutAddrMaskReps"
    },
    {
     "expr": "rate(node_netstat_Icmp_OutAddrMasks{instance=~\"$host\"}[5m]) or\nirate(node_netstat_Icmp_OutAddrMasks{instance=~\"$host\"}[5m])",
     "legendFormat": "OutAddrMasks"
    },
    {
     "expr": "rate(node_netstat_Icmp_InTimestampReps{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_Icmp_InTimestampReps{instance=~\"$host\"}[5m])",
     "legendFormat": "InTimestampReps"
    },
    {
     "expr": "rate(node_netstat_Icmp_InTimestamps{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_Icmp_InTimestamps{instance=~\"$host\"}[5m])",
     "legendFormat": "InTimestamps"
    },
    {
     "expr": "rate(node_netstat_Icmp_OutTimestampReps{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_Icmp_OutTimestampReps{instance=~\"$host\"}[5m])",
     "legendFormat": "OutTimestampReps"
    },
    {
     "expr": "rate(node_netstat_Icmp_OutTimestamps{instance=~\"$host\"}[$interval]) or\nirate(node_netstat_Icmp_OutTimestamps{instance=~\"$host\"}[5m])",
     "legendFormat": "OutTimestamps"
    }
   ]
  }
 ]
}