{
 "title": "System Overview",
 "tags": [
  "OS",
  "Percona"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(node_load1, instance)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<h1><i><font color=#5991A7><b><center>Data for </font><font color=#e68a00>Agoric Node</font> <font color=#5991A7> with</font> </font><font color=#e68a00>$interval</font> <font color=#5991A7>resolution</center></b></font></i></h1>"
  },
  {
   "title": "System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(node_time{instance=~\"$host\"} - node_boot_time{instance=~\"$host\"}) or (time() - node_boot_time{instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Virtual CPUs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(node_cpu{instance=~\"$host\",mode=~\"user\"}) or (1-absent(node_cpu{instance=~\"$host\",mode=~\"user\"}))) + sum(rdsosmetrics_General_numVCPUs{instance=~\"$host\"} or up * 0)"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(node_load1{instance=~\"$host\"}[$interval]) or avg_over_time(node_load1{instance=~\"$host\"}[5m])"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "pmm-singlestat-panel",
   "description": "Percent of Memory Available\nNote: on Modern Linux Kernels amount of Memory Available for application is not the same as Free+Cached+Buffers",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_memory_MemAvailable{instance=~\"$host\"} or (node_memory_MemFree{instance=~\"$host\"} + node_memory_Buffers{instance=~\"$host\"} + node_memory_Cached{instance=~\"$host\"})) / node_memory_MemTotal{instance=~\"$host\"} * 100"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "singlestat",
   "description": "RAM + SWAP",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$host\"}+node_memory_SwapTotal{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "singlestat",
   "description": "Sum of disk space on all partitions. Note  it can be significantly over-reported in some installations",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size{instance=~\"$host\",fstype=~\"(ext.|xfs|vfat)\"}) without (mountpoint)) without (device,fstype)"
    }
   ]
  },
  {
   "title": "Min Space Available",
   "type": "pmm-singlestat-panel",
   "description": "Lowest percent of the disk space available",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(node_filesystem_free{instance=~\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"}/node_filesystem_size{instance=~\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"})*100"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu{instance=~\"$host\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=~\"$host\",mode!=\"idle\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{instance=~\"$host\", mode!=\"total\", mode!=\"idle\"}[$interval]) or avg_over_time(node_cpu_average{instance=~\"$host\", mode!=\"total\", mode!=\"idle\"}[5m]))),100)",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "CPU Saturation and Max Core Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "(avg_over_time(node_procs_running{instance=~\"$host\"}[$interval])-1) / scalar(count(node_cpu{mode=\"user\", instance=~\"$host\"})) or (avg_over_time(node_procs_running{instance=~\"$host\"}[5m])-1) / scalar(count(node_cpu{mode=\"user\", instance=~\"$host\"}))",
     "legendFormat": "Normalized CPU Load"
    },
    {
     "calculatedInterval": "2s",
     "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu{instance=~\"$host\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=~\"$host\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
     "legendFormat": "Max CPU Core Utilization"
    }
   ]
  },
  {
   "title": "Interrupts and Context Switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_context_switches{instance=~\"$host\"}[$interval]) or irate(node_context_switches{instance=~\"$host\"}[5m])",
     "legendFormat": "Context Switches"
    },
    {
     "expr": "(rate(node_context_switches{instance=~\"$host\"}[$interval]) or irate(node_context_switches{instance=~\"$host\"}[5m])) / scalar(count(node_cpu{mode=\"user\", instance=~\"$host\"}))",
     "legendFormat": "Context Switches per Virtual CPU"
    },
    {
     "expr": "rate(node_intr{instance=~\"$host\"}[$interval]) or irate(node_intr{instance=~\"$host\"}[5m])",
     "legendFormat": "Interrupts"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(avg_over_time(node_procs_running{instance=~\"$host\"}[$interval]) - 1) or (avg_over_time(node_procs_running{instance=~\"$host\"}[5m]) -1)",
     "legendFormat": "Runnable Processes"
    },
    {
     "expr": "avg_over_time(node_procs_blocked{instance=~\"$host\"}[$interval]) or avg_over_time(node_procs_blocked{instance=~\"$host\"}[5m])",
     "legendFormat": "Blocked Processes"
    },
    {
     "expr": "rate(node_forks{instance=~\"$host\"}[$interval]) or irate(node_forks{instance=~\"$host\"}[5m])",
     "legendFormat": "Created Processes (Forks)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$host\"}",
     "legendFormat": "Total"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemFree{instance=~\"$host\"}",
     "legendFormat": "Free"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_Buffers{instance=~\"$host\"}",
     "legendFormat": "Buffers"
    },
    {
     "calculatedInterval": "2s",
     "expr": "max(node_memory_Cached{instance=~\"$host\",job=~\"rds-enhanced|linux\"}) without (job) or \nmax(node_memory_Cached{instance=~\"$host\",job=~\"rds-basic\"}) without (job)",
     "legendFormat": "Cached"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemTotal{instance=~\"$host\"} - (node_memory_MemFree{instance=~\"$host\"} + node_memory_Buffers{instance=~\"$host\"} + node_memory_Cached{instance=~\"$host\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Virtual Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemTotal{instance=~\"$host\"} + node_memory_SwapTotal{instance=~\"$host\"}",
     "legendFormat": "Total"
    },
    {
     "calculatedInterval": "2s",
     "expr": "(node_memory_MemAvailable{instance=~\"$host\"} or \n(node_memory_MemFree{instance=~\"$host\"} + node_memory_Buffers{instance=~\"$host\"} + node_memory_Cached{instance=~\"$host\"})) + \nnode_memory_SwapFree{instance=~\"$host\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_memory_MemTotal{instance=~\"$host\"} + node_memory_SwapTotal{instance=~\"$host\"} - \n((node_memory_MemAvailable{instance=~\"$host\"} or \n(node_memory_MemFree{instance=~\"$host\"} + node_memory_Buffers{instance=~\"$host\"} + node_memory_Cached{instance=~\"$host\"})) + \nnode_memory_SwapFree{instance=~\"$host\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Swap Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_SwapTotal{instance=~\"$host\"} - node_memory_SwapFree{instance=~\"$host\"}",
     "legendFormat": "Used"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_SwapFree{instance=~\"$host\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_SwapTotal{instance=~\"$host\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Swap Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "Bps", "label": "Swap out (-) / Swap in (+)" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pswpin{instance=~\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{instance=~\"$host\"}[5m]) * 4096",
     "legendFormat": "Swap In (Reads)"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pswpout{instance=~\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{instance=~\"$host\"}[5m]) * 4096",
     "legendFormat": "Swap Out (Writes)"
    },
    {
     "expr": "(rate(node_vmstat_pswpin{instance=~\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{instance=~\"$host\"}[5m]) * 4096) + (rate(node_vmstat_pswpout{instance=~\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{instance=~\"$host\"}[5m]) * 4096)",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "I/O Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "Bps", "label": "Page Out (-) / Page In (+)" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgin{instance=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=~\"$host\"}[5m]) * 1024",
     "legendFormat": "Disk Reads (Page In)"
    },
    {
     "calculatedInterval": "2s",
     "expr": "(rate(node_vmstat_pgpgout{instance=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=~\"$host\"}[5m]) * 1024)",
     "legendFormat": "Disk Writes (Page Out)"
    },
    {
     "expr": "(rate(node_vmstat_pgpgin{instance=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=~\"$host\"}[5m]) * 1024 ) + (rate(node_vmstat_pgpgout{instance=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=~\"$host\"}[5m]) * 1024)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Global File Descriptors Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_filefd_maximum{instance=~\"$host\"}",
     "legendFormat": "Limit"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_filefd_allocated{instance=~\"$host\"}",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "Disk IO Latency",
   "type": "graph",
   "description": "Shows average latency for Reads and Writes IO Devices.  Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems.  Higher than normal latency also can indicate internal storage problems.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(node_disk_read_time_ms{instance=~\"$host\"}[$interval])) / sum(rate(node_disk_reads_completed{instance=~\"$host\"}[$interval]))) or (sum(irate(node_disk_read_time_ms{instance=~\"$host\"}[5m])) / sum(irate(node_disk_reads_completed{instance=~\"$host\"}[5m])))\nor avg_over_time(aws_rds_read_latency_average{instance=~\"$host\"}[$interval]) or avg_over_time(aws_rds_read_latency_average{instance=~\"$host\"}[5m])",
     "legendFormat": "Read Latency"
    },
    {
     "expr": "(sum(rate(node_disk_write_time_ms{instance=~\"$host\"}[$interval])) / sum(rate(node_disk_writes_completed{instance=~\"$host\"}[$interval]))) or (sum(irate(node_disk_write_time_ms{instance=~\"$host\"}[5m])) / sum(irate(node_disk_writes_completed{instance=~\"$host\"}[5m])))\nor (avg_over_time(aws_rds_write_latency_average{instance=~\"$host\"}[$interval]) or avg_over_time(aws_rds_write_latency_average{instance=~\"$host\"}[5m]))",
     "legendFormat": "Write Latency"
    },
    {
     "expr": "(sum(rate(node_disk_read_time_ms{instance=~\"$host\"}[1h])) / sum(rate(node_disk_reads_completed{instance=~\"$host\"}[1h])))\nor avg_over_time(aws_rds_read_latency_average{instance=~\"$host\"}[1h]) or avg_over_time(aws_rds_read_latency_average{instance=~\"$host\"}[1h]) ",
     "legendFormat": "Avg Read Latency (1h)"
    },
    {
     "expr": "(sum(rate(node_disk_write_time_ms{instance=~\"$host\"}[1h])) / sum(rate(node_disk_writes_completed{instance=~\"$host\"}[1h]))) \nor (avg_over_time(aws_rds_write_latency_average{instance=~\"$host\"}[$interval]) or avg_over_time(aws_rds_write_latency_average{instance=~\"$host\"}[1h]))",
     "legendFormat": "Avg Write Latency (1h)"
    }
   ]
  },
  {
   "title": "Disk IO Load",
   "type": "graph",
   "description": "Shows how much disk was loaded for reads or writes as average number of outstanding requests at different period of time.  High disk load is a good measure of actual storage utilization. Different storage types handle load differently - some will show latency increases on low loads others can handle higher load with no problems.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Write Load (-) / Read Load (+)" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(node_disk_read_time_ms{instance=~\"$host\"}[$interval]))/1000 or sum(irate(node_disk_read_time_ms{instance=~\"$host\"}[5m]))/1000",
     "legendFormat": "Read Load"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(node_disk_write_time_ms{instance=~\"$host\"}[$interval]))/1000 or sum(irate(node_disk_write_time_ms{instance=~\"$host\"}[5m]))/1000",
     "legendFormat": "Write Load"
    },
    {
     "expr": "(sum(rate(node_disk_read_time_ms{instance=~\"$host\"}[$interval]))/1000 or sum(irate(node_disk_read_time_ms{instance=~\"$host\"}[5m]))/1000) + (sum(rate(node_disk_write_time_ms{instance=~\"$host\"}[$interval]))/1000 or sum(irate(node_disk_write_time_ms{instance=~\"$host\"}[5m]))/1000)",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "Bps", "label": "Outbound (-) / Inbound (+)" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_network_receive_bytes{instance=~\"$host\", device!=\"lo\"}[$interval])) or sum(irate(node_network_receive_bytes{instance=~\"$host\", device!=\"lo\"}[5m])) or sum(max_over_time(rdsosmetrics_network_rx{instance=~\"$host\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_rx{instance=~\"$host\"}[5m])) ",
     "legendFormat": "Inbound"
    },
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_network_transmit_bytes{instance=~\"$host\", device!=\"lo\"}[$interval])) or sum(irate(node_network_transmit_bytes{instance=~\"$host\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{instance=~\"$host\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_tx{instance=~\"$host\"}[5m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Network Utilization Hourly",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(increase(node_network_receive_bytes{instance=~\"$host\", device!=\"lo\"}[1h])) or sum(increase(rdsosmetrics_network_rx{instance=~\"$host\", device!=\"lo\"}[1h]))",
     "legendFormat": "Received"
    },
    {
     "calculatedInterval": "2s",
     "expr": "sum(increase(node_network_transmit_bytes{instance=~\"$host\", device!=\"lo\"}[1h])) or sum(increase(rdsosmetrics_network_tx{instance=~\"$host\", device!=\"lo\"}[1h]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "(sum(increase(node_network_receive_bytes{instance=~\"$host\", device!=\"lo\"}[1h]))+sum(increase(node_network_transmit_bytes{instance=~\"$host\", device!=\"lo\"}[1h])))  or (sum(increase(rdsosmetrics_network_rx{instance=~\"$host\", device!=\"lo\"}[1h]))+sum(increase(rdsosmetrics_network_tx{instance=~\"$host\", device!=\"lo\"}[1h])))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Local Network Errors",
   "type": "graph",
   "description": "Total Number of Local Network Interface Transmit Errors, Receive Errors and Drops.  Should be  Zero",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_network_receive_errs{instance=~\"$host\", device!=\"lo\"}[$interval])) or \nsum(irate(node_network_receive_errs{instance=~\"$host\", device!=\"lo\"}[5m]))",
     "legendFormat": "Receive Errors"
    },
    {
     "expr": "sum(rate(node_network_transmit_errs{instance=~\"$host\", device!=\"lo\"}[$interval])) or\nsum(irate(node_network_transmit_errs{instance=~\"$host\", device!=\"lo\"}[5m]))",
     "legendFormat": "Transmit Errors"
    },
    {
     "expr": "sum(rate(node_network_receive_drop{instance=~\"$host\", device!=\"lo\"}[$interval])) or\nsum(irate(node_network_receive_drop{instance=~\"$host\", device!=\"lo\"}[5m]))",
     "legendFormat": "Receive Drop"
    },
    {
     "expr": "sum(rate(node_network_transmit_drop{instance=~\"$host\", device!=\"lo\"}[$interval])) or \nsum(irate(node_network_transmit_drop{instance=~\"$host\", device!=\"lo\"}[5m]))",
     "legendFormat": "Transmit Drop"
    }
   ]
  },
  {
   "title": "TCP Retransmission",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_netstat_Tcp_RetransSegs{instance=~\"$host\"}[$interval]) or irate(node_netstat_Tcp_RetransSegs{instance=~\"$host\"}[5m])",
     "legendFormat": "Segments Retransmitted"
    },
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{instance=~\"$host\"}[$interval])/rate(node_netstat_Tcp_OutSegs{instance=~\"$host\"}[$interval]) or irate(node_netstat_Tcp_RetransSegs{instance=~\"$host\"}[5m])/irate(node_netstat_Tcp_OutSegsSegs{instance=~\"$host\"}[5m])",
     "legendFormat": "Retransmit Ratio"
    }
   ]
  }
 ]
}